GET http://localhost:3000/clients

###Create Product
POST http://localhost:3000/clients
Content-Type: application/json

{
    "ci": "34123123",
    "name": "Iturri",
    "email": "ichu@gmail.com",
    "password": "lmao", 
    "phone": "712456",
    "address": "Chapare",
    "pets": []
}

###GET by id
GET http://localhost:3000/clients/665a79bf4b025d479382b522

###PATCH by id
PATCH http://localhost:3000/clients/123123
Content-Type: application/json

{
    "address": "Homeless"
}

###DELETE by id
DELETE http://localhost:3000/clients/66468b6fb26c0e1f34d49128

###ERROR 
GET http://localhost:3000/asdadas

###GET by Ci
GET http://localhost:3000/clients/ci/98456

###DELETE by CI
DELETE  http://localhost:3000/clients/ci/8463783